language: android

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "OkOy1wuRZCnzbLHX+Kykf8HSbJVrTSa7vEfxAAI5cagwjFM7W9AwdQMt1GewvM3B/1ToTgXJCesaqNBu3o8oyHP1xe/jWO1b4bM16iuW+zrj4nfGQBEnf1LtDCX24Q+QMJyK+kT6dMXGFUSaZGk6UqMi3sEoQTeEhkT2bedrPt9EbLLzAHx1FG3S5ER5DjqHpd8UB6oL5SfXwqVQWHcX92o5kO2Q3LTTkm+xYTus6tyZCL4G8iYPHLDzTFvUy26HtrVt76blDF8CbkDdC+OWDn+oH87T+IPouftZ3Fdj6PJKJ5wUVOMVD5hlm0Eenbrynmm5eGVQEF8zYMFUpZMRHzN33ZZUIitDWsaBpGJud9nSYV5+5Hioh/1ief4VWuoCEEinjF+n+mBCFjfwrg72FwNSuu3HaKLsz02dhlvgG/uyK/hdM8bWmupW0VL4zvnlIQ8VBydqRfF9mWVxGRkiCrKD17GGqTm3R8OIhEufisjUHYGo6gOxBv2T17vrU3RICDK7nlelMqIZjLiVxZJqX0SMUpq5BEmhiWleelERlDZVP6GpEV0y8oQT03gT0X2j6d4Bws+O3823L2t1OxlAlNTAQE0ArAaO0oQ0gLKWkT37JoV6XVk9O9EckvaMJUPRlm7oKfmn5kvcszdFKobCORuefELNFOlO82cwUSs7XhU="
    - secure: "M+bs0M4VI9GSJ3N1BeFafG0Rjis/Itxrsfc3TQXeYLMTQXYmE3kMrLvRYgeC0PY/F+sTkt+1FezYrfNaU/H8/9JV2XQSOERfSWv21+XOROsUbK8JWfAIPKlEGGSzPdS4Y+USftSEIuXCunZOzD/gLKMw7PbjdmnnAP2F2qPwpNCY6sLa/tzzlz1iFe6XuOLygVv20rJCB1Q+6gqle/+yYS44ZBHdSNJcFCye86Vtvw+BnpUgiqcf4qRwc9JAp/tLxjQBDmmPv/SPQfLYBOSF2xv/9C+rp1B75u5X9kFL/7X+z2DpOlNj6y1lmIMaWd513bkGV04nlfoCeycVI/zb2PbxmHBNluV8Ei9ack81b+KK+Nj5Ed4Pm/ruDbqVf8WVxDNrcidVZihc9avTgqL/sVq/ePxxP7LYruf3OuAElcb/EU4HtT3DQmYRRATVnarA+kuxWmH6qIFxEU7zHsHiWjxODsXhWdCWgkePtbUMCbGuHNFHX3Oo6T2Vk0QhpcvvYkSA/x45MHamDUqLA1AKHhfiaQHnWryKIVIwp71Pd9Zb8T+Etd/5foYwBJ5EY/VRIZbMyfp2OcbFKHX6qyG36CvX0CH1CmORz0CCklZtaQjix/xQ3XlAHhLEBhTI3gHIy8jftd5ny4GplJ7LFZ10FSnodgf7XZFsHOV652ROb0g="

branches:
  except:
    - gh-pages

notifications:
  email: false
